version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  reviewers:
  - paul58914080
  ignore:
  - dependency-name: org.springdoc:springdoc-openapi-ui
    versions:
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: com.google.cloud.tools:jib-maven-plugin
    versions:
    - 2.7.1
    - 2.8.0
  - dependency-name: com.github.cukedoctor:cukedoctor-maven-plugin
    versions:
    - 3.5.2
  - dependency-name: com.societegenerale.commons:arch-unit-maven-plugin
    versions:
    - 2.7.1
    - 2.7.2
  - dependency-name: org.projectlombok:lombok
    versions:
    - 1.18.18
